server:
  port: 8088 #端口号
  servlet:
    context-path: /springboot #项目根路径


spring:
  jpa:
  hibernate:
    ddl-auto: udpate
    show-sql: true
  jackson:
    date-formate: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serilaization:
      write-dates-as-timestamps: false
  thymeleaf:
    prefix: classpath:/templates/
  redis:
    host: localhost
    port: 6379
    max-wait: 30000
    max-active: 100
    max-idle: 20
    min-idle: 0
    timeout: 3000
